# Generated by Django 5.1.7 on 2025-03-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
