# Generated by Django 5.1.7 on 2025-03-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_customuser_following_story_comment_like'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
